.TH ARBITRONSORT "8" "Project Cyrus" "CMU"
.SH NAME
arbitronsort \- sorts arbitron(8) output
.SH SYNOPSIS
.B 
arbitronsort
.SH DESCRIPTION
.PP
This tool takes the output of arbitron (run without the -o option)
on stdin and prints out first a ranking of mailboxes by number of 
people who selected the mailbox, and then a ranking of mailbox by
number of subscribers.
.SH SEE ALSO
.PP
\fBarbitron(8)\fR
